//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_UX.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class German {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal German() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("P_UX.Resources.German", typeof(German).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tickets kaufen.
        /// </summary>
        internal static string btnBuyTickets {
            get {
                return ResourceManager.GetString("btnBuyTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abbrechen.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voller Tarif.
        /// </summary>
        internal static string btnFullFare {
            get {
                return ResourceManager.GetString("btnFullFare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reduzierter Tarif.
        /// </summary>
        internal static string btnHalfFare {
            get {
                return ResourceManager.GetString("btnHalfFare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Navigo Pass aufladen.
        /// </summary>
        internal static string btnPassNavigo {
            get {
                return ResourceManager.GetString("btnPassNavigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rückgabe.
        /// </summary>
        internal static string btnReturn {
            get {
                return ResourceManager.GetString("btnReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à     Fahrkarte Fughafen                        Roissy-Charles de Gaulles, Orly.
        /// </summary>
        internal static string btnTicketAirport {
            get {
                return ResourceManager.GetString("btnTicketAirport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à     Fahrkarte Disneyland Paris            Gültig ab dieser Haltestelle.
        /// </summary>
        internal static string btnTicketDisney {
            get {
                return ResourceManager.GetString("btnTicketDisney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à     Fahrkarte Mobilis                             1 Tag ohne Zugang zum Flughafen.
        /// </summary>
        internal static string btnTicketMobilis {
            get {
                return ResourceManager.GetString("btnTicketMobilis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à     Fahrkarte für Paris Region              Gültig ab dieser Haltestelle.
        /// </summary>
        internal static string btnTicketParisRegion {
            get {
                return ResourceManager.GetString("btnTicketParisRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à     Fahrkarte Paris Besuch                   1,2,3 oder 5 Tage.
        /// </summary>
        internal static string btnTicketParisVisit {
            get {
                return ResourceManager.GetString("btnTicketParisVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à     Fahrkarte t+                                      U-Bahn, Bus, Straßenbahn, RER in Paris.
        /// </summary>
        internal static string btnTicketT {
            get {
                return ResourceManager.GetString("btnTicketT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Treffen Sie Ihre Entscheidung.
        /// </summary>
        internal static string lblTitleTicketsSelection {
            get {
                return ResourceManager.GetString("lblTitleTicketsSelection", resourceCulture);
            }
        }
    }
}
