//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_UX.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Spanish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Spanish() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("P_UX.Resources.Spanish", typeof(Spanish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comprar.
        /// </summary>
        internal static string btnAddTickets {
            get {
                return ResourceManager.GetString("btnAddTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Añadir al pedido.
        /// </summary>
        internal static string btnAddToOrder {
            get {
                return ResourceManager.GetString("btnAddToOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comprar otros billetes.
        /// </summary>
        internal static string btnBuyOtherTickets {
            get {
                return ResourceManager.GetString("btnBuyOtherTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comprar billetes.
        /// </summary>
        internal static string btnBuyTickets {
            get {
                return ResourceManager.GetString("btnBuyTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Anular.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tarjeta.
        /// </summary>
        internal static string btnCard {
            get {
                return ResourceManager.GetString("btnCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dinero.
        /// </summary>
        internal static string btnCash {
            get {
                return ResourceManager.GetString("btnCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 5 días.
        /// </summary>
        internal static string btnFiveDays {
            get {
                return ResourceManager.GetString("btnFiveDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 5 billetes.
        /// </summary>
        internal static string btnFiveTimes {
            get {
                return ResourceManager.GetString("btnFiveTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 4 billetes.
        /// </summary>
        internal static string btnFourTimes {
            get {
                return ResourceManager.GetString("btnFourTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pleno tarifa.
        /// </summary>
        internal static string btnFullFare {
            get {
                return ResourceManager.GetString("btnFullFare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proceder al pago.
        /// </summary>
        internal static string btnGoPay {
            get {
                return ResourceManager.GetString("btnGoPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tarifa reducido.
        /// </summary>
        internal static string btnHalfFare {
            get {
                return ResourceManager.GetString("btnHalfFare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 8 billetes.
        /// </summary>
        internal static string btnHeightTimes {
            get {
                return ResourceManager.GetString("btnHeightTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1 billete.
        /// </summary>
        internal static string btnOnce {
            get {
                return ResourceManager.GetString("btnOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1 día.
        /// </summary>
        internal static string btnOneDay {
            get {
                return ResourceManager.GetString("btnOneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recargar Navigo Pass.
        /// </summary>
        internal static string btnPassNavigo {
            get {
                return ResourceManager.GetString("btnPassNavigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Atrás.
        /// </summary>
        internal static string btnReturn {
            get {
                return ResourceManager.GetString("btnReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 7 billetes.
        /// </summary>
        internal static string btnSevenTimes {
            get {
                return ResourceManager.GetString("btnSevenTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6 billetes.
        /// </summary>
        internal static string btnSixTimes {
            get {
                return ResourceManager.GetString("btnSixTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3 días.
        /// </summary>
        internal static string btnThreeDays {
            get {
                return ResourceManager.GetString("btnThreeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3 billetes.
        /// </summary>
        internal static string btnThreeTimes {
            get {
                return ResourceManager.GetString("btnThreeTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à     Billete de aeropuerto                       Roissy-Charles de Gaulles, Orly.
        /// </summary>
        internal static string btnTicketAirport {
            get {
                return ResourceManager.GetString("btnTicketAirport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à     Billete Disneyland Paris                     Válido desde esta estación.
        /// </summary>
        internal static string btnTicketDisney {
            get {
                return ResourceManager.GetString("btnTicketDisney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à     Billete Mobilis                                       1 día sin acceso al aeropuerto.
        /// </summary>
        internal static string btnTicketMobilis {
            get {
                return ResourceManager.GetString("btnTicketMobilis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à     Billete para Paris Region                  Válido desde esta estación.
        /// </summary>
        internal static string btnTicketParisRegion {
            get {
                return ResourceManager.GetString("btnTicketParisRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à     Billete Paris Visita                               1,2,3 o 5 días.
        /// </summary>
        internal static string btnTicketParisVisit {
            get {
                return ResourceManager.GetString("btnTicketParisVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à     Billete t+                                              Metro, Bus, Tram, RER en Paris.
        /// </summary>
        internal static string btnTicketT {
            get {
                return ResourceManager.GetString("btnTicketT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2 billetes.
        /// </summary>
        internal static string btnTwice {
            get {
                return ResourceManager.GetString("btnTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Billetes aceptados.
        /// </summary>
        internal static string lblAcceptedBills {
            get {
                return ResourceManager.GetString("lblAcceptedBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tarjetas aceptadas.
        /// </summary>
        internal static string lblAcceptedCard {
            get {
                return ResourceManager.GetString("lblAcceptedCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Monedas aceptadas.
        /// </summary>
        internal static string lblAcceptedCoins {
            get {
                return ResourceManager.GetString("lblAcceptedCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Importe.
        /// </summary>
        internal static string lblAmount {
            get {
                return ResourceManager.GetString("lblAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Indica el número de billetes deseados.
        /// </summary>
        internal static string lblChoseNbrTickets {
            get {
                return ResourceManager.GetString("lblChoseNbrTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de pila.
        /// </summary>
        internal static string lblCustomerFirstName {
            get {
                return ResourceManager.GetString("lblCustomerFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre.
        /// </summary>
        internal static string lblCustomerLastName {
            get {
                return ResourceManager.GetString("lblCustomerLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à del.
        /// </summary>
        internal static string lblDateFrom {
            get {
                return ResourceManager.GetString("lblDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à al.
        /// </summary>
        internal static string lblDateTo {
            get {
                return ResourceManager.GetString("lblDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Número de billetes.
        /// </summary>
        internal static string lblNbrTickets {
            get {
                return ResourceManager.GetString("lblNbrTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tarifa.
        /// </summary>
        internal static string lblRate {
            get {
                return ResourceManager.GetString("lblRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validez del billete.
        /// </summary>
        internal static string lblTicketValidity {
            get {
                return ResourceManager.GetString("lblTicketValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Elija un método de pago.
        /// </summary>
        internal static string lblTitleOptionPayment {
            get {
                return ResourceManager.GetString("lblTitleOptionPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resumen de la orden.
        /// </summary>
        internal static string lblTitleOrderResume {
            get {
                return ResourceManager.GetString("lblTitleOrderResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Billete Paris Visita.
        /// </summary>
        internal static string lblTitleParisVisit {
            get {
                return ResourceManager.GetString("lblTitleParisVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Order payment.
        /// </summary>
        internal static string lblTitlePayment {
            get {
                return ResourceManager.GetString("lblTitlePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Elige el número de billetes que deseados.
        /// </summary>
        internal static string lblTitleTicketPrices {
            get {
                return ResourceManager.GetString("lblTitleTicketPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Título.
        /// </summary>
        internal static string lblTitleTickets {
            get {
                return ResourceManager.GetString("lblTitleTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Haga su elección.
        /// </summary>
        internal static string lblTitleTicketsSelection {
            get {
                return ResourceManager.GetString("lblTitleTicketsSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pago de la orden.
        /// </summary>
        internal static string lblTotalAmountToPay {
            get {
                return ResourceManager.GetString("lblTotalAmountToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total a pagar.
        /// </summary>
        internal static string lblTotalToPay {
            get {
                return ResourceManager.GetString("lblTotalToPay", resourceCulture);
            }
        }
    }
}
